name: Update Earthquake Data

on:
  schedule:
    # Run every 6 hours to keep data fresh
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pandas
    - name: Update earthquake data
      run: |
        python update_earthquake_data_github.py
        
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if ! git diff --cached --quiet; then
          git commit -m "🌍 Auto-update earthquake data - $(date '+%Y-%m-%d %H:%M:%S UTC')"
          git push origin main
        else
          echo "No changes to commit"
        fi
